// ============================================================
// Financial Management System (FMS) — Log Types
// constants/LogTypes/FMS_LOG_TYPES.js
// ============================================================

export const FMS_LOG_TYPES = {

  //#region BUDGET
  FMS_BUDGET_ALLOTMENTS:                                "FMS_BUDGET_ALLOTMENTS",
  FMS_BUDGET_APPROPRIATIONS:                            "FMS_BUDGET_APPROPRIATIONS",
  FMS_BUDGET_BURS:                                      "FMS_BUDGET_BURS",
  FMS_BUDGET_GAAS:                                      "FMS_BUDGET_GAAS",
  FMS_BUDGET_PPAS:                                      "FMS_BUDGET_PPAS",
  FMS_BUDGET_SAROS:                                     "FMS_BUDGET_SAROS",
  //#endregion

  //#region STATIC DATA
  FMS_STATICDATA_ACCOUNTABLEFORMS:                      "FMS_STATICDATA_ACCOUNTABLEFORMS",
  FMS_STATICDATA_ACCOUNTCLASSIFICATIONS:                "FMS_STATICDATA_ACCOUNTCLASSIFICATIONS",
  FMS_STATICDATA_ALLOTMENTSOURCEDOCUMENTTYPES:          "FMS_STATICDATA_ALLOTMENTSOURCEDOCUMENTTYPES",
  FMS_STATICDATA_AUTHORIZATIONCODES:                    "FMS_STATICDATA_AUTHORIZATIONCODES",
  FMS_STATICDATA_BANKS:                                 "FMS_STATICDATA_BANKS",
  FMS_STATICDATA_BANKBRANCHES:                          "FMS_STATICDATA_BANKBRANCHES",
  FMS_STATICDATA_BANKACCOUNTS:                          "FMS_STATICDATA_BANKACCOUNTS",
  FMS_STATICDATA_BUR:                                   "FMS_STATICDATA_BUR",
  FMS_STATICDATA_CLIENTS:                               "FMS_STATICDATA_CLIENTS",
  FMS_STATICDATA_DOCUMENTTYPES:                         "FMS_STATICDATA_DOCUMENTTYPES",
  FMS_STATICDATA_FINANCINGSOURCES:                      "FMS_STATICDATA_FINANCINGSOURCES",
  FMS_STATICDATA_FUNDCATEGORIES:                        "FMS_STATICDATA_FUNDCATEGORIES",
  FMS_STATICDATA_FUNDCATEGORYTYPES:                     "FMS_STATICDATA_FUNDCATEGORYTYPES",
  FMS_STATICDATA_FUNDCLUSTERS:                          "FMS_STATICDATA_FUNDCLUSTERS",
  FMS_STATICDATA_FUNDINGSOURCES:                        "FMS_STATICDATA_FUNDINGSOURCES",
  FMS_STATICDATA_FUNDSUBCATEGORIES:                     "FMS_STATICDATA_FUNDSUBCATEGORIES",
  FMS_STATICDATA_GENERALLEDGERS:                        "FMS_STATICDATA_GENERALLEDGERS",
  FMS_STATICDATA_OBJECTCODES:                           "FMS_STATICDATA_OBJECTCODES",
  FMS_STATICDATA_PROGRAMS:                              "FMS_STATICDATA_PROGRAMS",
  FMS_STATICDATA_RESPONSIBILITYCENTERS:                 "FMS_STATICDATA_RESPONSIBILITYCENTERS",
  FMS_STATICDATA_SUBOBJECTCODES:                        "FMS_STATICDATA_SUBOBJECTCODES",
  FMS_STATICDATA_SUBSIDIARYLEDGERS:                     "FMS_STATICDATA_SUBSIDIARYLEDGERS",
  FMS_STATICDATA_TRANSACTIONTYPES:                      "FMS_STATICDATA_TRANSACTIONTYPES",
  //#endregion

};