import createMockResourceAPI from "@/helpers/rtk_mock_resource_factory";

const mockTransactionData = [
  {
    refNumber: "DVF2025-06-00001",
    date: "06/02/2025",
    particulars: "Payment of Office Supplies for the month of May 2025 per Sales Invoice No. 6348 dated May 15, 2025",
    amount: 25000.0,
    fund: "Regular Agency Fund - General Fund",
    remarks: "For immediate payment",
    templateCode: "DJE001",
  },
  {
    refNumber: "DVF2V-2025-03-00001",
    date: "06/03/2025",
    particulars:
      "Payment for Phase 2 Bids to Contractors - Payment for the 15% Mobilization fee for the Six Storey East Wing Building MOOE/BLDG CONSTRUCTION",
    amount: 59820000.0,
    fund: "Infrastructure Development Fund",
    remarks: "Phase 2 construction payment - Major construction project",
    templateCode: "DJE009",
  },
  {
    refNumber: "DVF2025-06-00002",
    date: "06/04/2025",
    particulars: "Payment for fuel consumption of MADA patrol boats for emergency response with the May 2025",
    amount: 15000000.0,
    fund: "Regular Agency Fund - General Fund",
    remarks: "Monthly fuel allocation",
    templateCode: "DJE001",
  },
  {
    refNumber: "DVF2025-06-00003",
    date: "06/04/2025",
    particulars: "Payment of hazard pay for traffic enforcers and head count employees for May 2025",
    amount: 752225.98,
    fund: "Regular Agency Fund - General Fund",
    remarks: "Monthly hazard pay",
    templateCode: "DJE001",
  },
  {
    refNumber: "DVF2025-06-00004",
    date: "06/06/2025",
    particulars: "Payment for IT equipment and Software licenses for office modernization project",
    amount: 12600000.0,
    fund: "Special Agency Fund",
    remarks: "IT modernization phase 1",
    templateCode: "DJE002",
  },
  {
    refNumber: "CDU2025-06-00102",
    date: "06/02/2025",
    particulars: "Collection of Business Tax for June 2025",
    amount: 150000.0,
    fund: "General Fund",
    remarks: "Daily collection",
    templateCode: "CDU001",
  },
  {
    refNumber: "CDU2025-06-00158",
    date: "06/03/2025",
    particulars: "Collection of environmental fees from commercial establishments along EDSA and C5 Road",
    amount: 180000000.0,
    fund: "Environmental Management Fund",
    remarks: "Monthly environmental fee collection",
    templateCode: "CDU002",
  },
  {
    refNumber: "CDU2025-06-00159",
    date: "06/04/2025",
    particulars: "Collection of parking fees from designated parking areas in Central Business District and Ortigas Business Districts",
    amount: 155000000.0,
    fund: "Traffic Management Fund",
    remarks: "Daily parking fee collection",
    templateCode: "CDU003",
  },
  {
    refNumber: "CDU2025-06-00170",
    date: "06/04/2025",
    particulars: "Collection of traffic violation fees from Metro Manila Traffic Violator System for the month of May 2025",
    amount: 260731186.42,
    fund: "Traffic Management Fund",
    remarks: "Monthly violation fee collection",
    templateCode: "CDU001",
  },
  {
    refNumber: "CDU2025-06-00171",
    date: "06/06/2025",
    particulars: "Collection of permit fees and regulatory charges from business establishments",
    amount: 44300000.0,
    fund: "Regulatory Fund",
    remarks: "Quarterly permit fee collection",
    templateCode: "CDU002",
  },
  {
    refNumber: "DEP2025-06-00105",
    date: "06/02/2025",
    particulars: "Deposit of June 2, 2025 Collections",
    amount: 175000.0,
    fund: "General Fund",
    remarks: "Daily deposit",
    templateCode: "DEP001",
  },
  {
    refNumber: "DEP2025-06-00106",
    date: "06/03/2025",
    particulars: "Deposit of June 3, 2025 Collections to Land Bank of the Philippines",
    amount: 124000000.0,
    fund: "General Fund",
    remarks: "Daily bank deposit",
    templateCode: "DEP001",
  },
  {
    refNumber: "DEP2025-06-00118",
    date: "06/04/2025",
    particulars: "Deposit of special collection and fees to Authorized Government Depository Bank",
    amount: 69750000.0,
    fund: "Special Fund",
    remarks: "Special collection deposit",
    templateCode: "DEP001",
  },
  {
    refNumber: "DEP2025-06-00134",
    date: "06/05/2025",
    particulars: "Deposit of trust fund collections to Bureau of Treasury",
    amount: 50000000.0,
    fund: "Trust Fund",
    remarks: "Trust fund deposit",
    templateCode: "DEP001",
  },
  {
    refNumber: "DEP2025-06-00135",
    date: "06/06/2025",
    particulars: "Deposit of end of day collections from all MADA offices",
    amount: 198500000.0,
    fund: "General Fund",
    remarks: "End of day deposit",
    templateCode: "DEP001",
  },
];

export const mockTransactionInboxesAPI = createMockResourceAPI({
  resource: "TransactionInboxes",
  idKey: "transactionInboxId",
  tagTypes: ["MockFMS", "TransactionInboxes"],
  mockData: mockTransactionData,
  lookupMap: ({ transactionInboxId, transactionInboxName }) => ({
    value: transactionInboxId,
    label: transactionInboxName,
  }),
  delay: 0,
});

export const {
  useGetTransactionInboxesQuery,
  useFindTransactionInboxesQuery,
  useLookUpTransactionInboxesMutation,
  useDeleteTransactionInboxesMutation,
  useSaveTransactionInboxesMutation,
  useExportTransactionInboxesMutation,
  useResetTransactionInboxesMutation,
} = mockTransactionInboxesAPI;
